name: Deploy S3 Bucket

on:
  push:
    branches:
      - main

jobs:
  deploy:
    uses: aliasgar-kaeed-challawala/terraform-reusable-template/.github/workflows/reusable-terraform.yml@main
    with:
      tf_version: "1.5.7"
    secrets:
      AWS_REGION: ${{ secrets.AWS_REGION }}
